name: noaa-aeromagnetic
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - numba
  - jupyter
  - jupyterlab
  - netcdf4
  - pyproj
  - tqdm
  - pygmt==0.4.1
  - gmt==6.2.0
  # Fatiando
  - pooch==1.5.1
  - verde==1.6.1
